spring:
  application.name: config

---
spring:
  profiles: local
  cloud:
    config.server.git.uri: "file:../properties"

server.port: 18080

eureka:
  client:
    region: default
    serviceUrl.defaultZone: http://localhost:18081/eureka/